name: Bugmelding
description: Meld een bug die je bent tegengekomen op de server
title: "[Bug] "
labels: ["bug", "new"]
body:
  - type: markdown
    attributes:
      value: |
        Bedankt dat je een bug wilt melden bij Nieuweveen Roleplay!  
        Vul het onderstaande formulier zo duidelijk en compleet mogelijk in.  
        Hoe beter jouw uitleg, hoe sneller wij het kunnen oplossen.

  - type: input
    id: contact
    attributes:
      label: Contactgegevens
      description: Hoe kunnen we je bereiken via Discord als we vragen hebben?
      placeholder: bijv. Skai#0001
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: Wat gebeurde er precies?
      description: Beschrijf duidelijk wat er fout ging, inclusief eventuele foutmeldingen of console-info.
      placeholder: |
        Voorbeeld: "Ik kreeg een notificatie: 'Er ging iets mis, probeer het opnieuw.'"
        Ook verscheen er een foutmelding in mijn F8-console.
    validations:
      required: true

  - type: textarea
    id: what-should-happen
    attributes:
      label: Wat had er moeten gebeuren?
      description: Wat had er volgens jou normaal moeten gebeuren in plaats van de bug?
      placeholder: Beschrijf het verwachte gedrag van het systeem.

  - type: textarea
    id: repro
    attributes:
      label: Hoe kunnen wij de bug reproduceren?
      description: Beschrijf stapsgewijs wat we moeten doen om dezelfde bug te zien.
      placeholder: |
        Voorbeeld: 1. Zet een zak op je hoofd  
                  2. Doe een dansje  
                  3. Je wordt ineens geteleporteerd naar een andere plek
    validations:
      required: false

  - type: dropdown
    id: frequency
    attributes:
      label: Frequentie van de bug
      description: Hoe vaak komt deze bug voor?
      options:
        - Altijd
        - Meerdere keren per dag
        - 1x per dag
        - 1x per week
        - Heel zelden
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact van de bug
      description: Hoeveel invloed heeft deze bug op de gameplay?
      options:
        - Hoog (veel spelers hebben er last van)
        - Laag (kleine hinder)
        - Geen merkbare impact

  - type: textarea
    id: logs
    attributes:
      label: Logbestanden of console errors
      description: Voeg hier relevante logs of foutmeldingen toe (bijv. uit F8-console).
      placeholder: Kopieer je log hier, of sleep een logbestand in dit vak.

  - type: checkboxes
    id: richtlijnen
    attributes:
      label: Bevestiging
      description: Door deze issue in te dienen, ga je akkoord met de regels zoals beschreven in ons bijdragen-document.
      options:
        - label: Ik heb de richtlijnen gelezen en ga ermee akkoord
          required: true
