name: EUP/Kleding Issue
description: Meld een probleem met EUP, kleding of textures
title: "[EUP] "
labels: ["bug", "EUP - interiors - retextures", "new"]
body:
  - type: markdown
    attributes:
      value: |
        Bedankt dat je een EUP/kleding-gerelateerd probleem wilt melden bij Nieuweveen Roleplay!  
        Vul onderstaand formulier zo duidelijk mogelijk in, zodat wij je snel kunnen helpen.

  - type: input
    id: contact
    attributes:
      label: Contactgegevens
      description: Hoe kunnen we je bereiken via Discord als we vragen hebben?
      placeholder: bijv. Skai#0001
    validations:
      required: false

  - type: input
    id: goedkeuring
    attributes:
      label: Goedgekeurd door
      description: Is dit probleem gemeld met goedkeuring van iemand van het team? Vul dan zijn/haar Discord-tag in.
      value: "N.V.T."

  - type: dropdown
    id: where
    attributes:
      label: Waar hoort dit probleem bij?
      options:
        - EUP/Kleding
        - Interiors
        - Andere textures
    validations:
      required: true

  - type: textarea
    id: what-wrong
    attributes:
      label: Wat klopt er niet?
      description: Beschrijf wat er niet klopt aan de kleding, EUP of textures. Voeg eventueel screenshots toe.
      placeholder: |
        Voorbeeld: "De kleding van de ambulance is vanaf een afstand geel i.p.v. rood."

  - type: checkboxes
    id: richtlijnen
    attributes:
      label: Bevestiging
      description: Door deze issue in te dienen, ga je akkoord met de [contributing-richtlijnen](https://github.com/nieuweveen/development/blob/master/CONTRIBUTING.md).
      options:
        - label: Ik heb de richtlijnen gelezen en ga ermee akkoord
          required: true
