name: Feature request
description: Vraag een nieuwe feature aan voor Nieuweveen Roleplay
title: "[FEATURE]: "
labels: ["enhancement", "new"]
body:
  - type: markdown
    attributes:
      value: |
        Welkom bij Nieuweveen Roleplay! 🏘️
        
        Bedankt dat je de tijd wilt nemen om een feature request aan te maken!
        Vul de onderstaande velden aub zo gedetailleerd mogelijk in zodat ons development team de request snel kan beoordelen en implementeren.
        
        **Wanneer je langere teksten maakt vergeet dan niet gebruik te maken van OPMAAK! (headings/kopjes per onderwerp etc)**
        Dit zorgt ervoor dat het overzichtelijk blijft en we je feature request waarschijnlijk sneller oppakken.
        
        Voor opmaak hulp zie [Markdown-Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) (Dit is sws handig om te weten want werkt ook volledig in Discord berichten)
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Hoe kunnen we je contacteren op Discord als we extra informatie nodig hebben?
      placeholder: "Voorbeeld: BurgermeesterPiet#1337"
    validations:
      required: false
  - type: input
    id: goedkeuring
    attributes:
      label: Goedgekeurd door staff
      description: Is deze feature request door een stafflid goedgekeurd? Zo ja, vul dan hier de persoon z'n Discord tag in.
      value: "N.V.T."
  - type: dropdown
    id: categorie
    attributes:
      label: Feature Categorie
      description: Onder welke categorie valt deze feature?
      options:
        - Voertuigen/Vehicles
        - Jobs/Banen
        - Housing/Huizen
        - Economy/Economie
        - Crime/Crimineel
        - Government/Overheid
        - Medical/Medisch
        - Mechanics/Monteurs
        - Clothing/Kleding
        - UI/Interface
        - Events/Evenementen
        - Quality of Life
        - Anders
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: "Beschrijf zo duidelijk mogelijk de gewenste feature"
      description: "Leg uit wat je voor ogen hebt. Hoe zou het moeten werken? Wat zijn de belangrijkste functionaliteiten?"
      placeholder: |
        Bijvoorbeeld:
        ## Nieuwe baan: Vuilnisman
        
        ### Beschrijving
        Een nieuwe baan waarbij spelers afval kunnen ophalen door de stad...
        
        ### Hoe het werkt
        1. Spelers gaan naar het depot
        2. Ze pakken een vuilniswagen
        3. Ze rijden langs vooraf bepaalde routes...
    validations:
      required: true
  - type: textarea
    id: roleplay-impact
    attributes:
      label: "Roleplay Impact"
      description: "Hoe zou deze feature de roleplay ervaring verbeteren? Welke nieuwe mogelijkheden creëert het?"
    validations:
      required: true
  - type: textarea
    id: solves
    attributes:
      label: "Wat lost deze feature op?"
      description: "Welk probleem of welke behoefte lost deze feature op? Zijn er klachten of verzoeken van spelers geweest?"
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: "Extra informatie"
      description: "Eventuele screenshots, voorbeelden van andere servers, of andere relevante informatie"
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Richtlijnen
      description: Door deze feature request aan te maken ga je akkoord met onze [contributing](https://github.com/Nieuweveen-Roleplay/development/blob/master/CONTRIBUTING.md) richtlijnen
      options:
        - label: Ik ga akkoord met de feature request richtlijnen en heb deze aandachtig gelezen
          required: true
        - label: Ik heb gecontroleerd of deze feature niet al eerder is aangevraagd
          required: true
